[supervisord]
user=root
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid
stopsignal=TERM

[program:ocserv]
command=${OC_SCRIPTS_DIR}/ocserv.sh
priority=1
autostart=true
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10
killasgroup=true
stopasgroup=true

[program:occlient]
command=${OC_SCRIPTS_DIR}/occlient.sh
priority=10
autostart=%(ENV_OC_CLIENT_ENABLE)s
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10
killasgroup=true
stopasgroup=true

[program:ocsplit]
command=${OC_SCRIPTS_DIR}/ocsplit.sh
priority=20
autostart=%(ENV_OC_SPLIT_ENABLE)s
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10
killasgroup=true
stopasgroup=true

[program:custom]
command=${OC_SCRIPTS_DIR}/custom.sh
priority=30
autostart=true
autorestart=false
startsecs=0
startretries=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
